LAYER_LOCK_ENABLE = yes
COMBO_ENABLE = yes
MOUSEKEY_ENABLE = yes
# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_DRIVER = azoteq_iqs5xx
SPLIT_KEYBOARD = yes
# SPLIT_POINTING_ENABLE = yes
# CONSOLE_ENABLE = yes
# I2C_DRIVER_REQUIRED = yes
# 分割がUARTなら（GP8/GP9を使う前提）
SERIAL_DRIVER = vendor
